models.py
import datetime
import re

from app import db


def slugify(s):
    return re.sub('[^\w]+', '-', s).lower()


entry_tags = db.Table('entry_tags',
                      db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                      db.Column('entry_id', db.Integer,
                                db.ForeignKey('entry.id'))
                      )


class Entry(db.Model):
    """docstring for Entry"""
    STATUS_PUBLIC = 0
    STATUS_DRAFT = 1
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)
    body = db.Column(db.Text)
    status =db.Column(db.SmallInteger, default=STATUS_PUBLIC)
    created_timestamp = db.Column(db.DateTime, default=datetime.datetime.now)
    modified_timestamp = db.Column(
        db.DateTime, default=datetime.datetime.now, onupdate=datetime.datetime.now)

    tags = db.relationship('Tag', secondary=entry_tags,
                           backref=db.backref('entries', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        # call the parent constructor
        super(Entry, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        self.slug = ''
        if self.title:
            self.slug = slugify(self.title)

    def __reper(self):
        return '<Entry: %s>' % self.title


class Tag(db.Model):
    """docstring for Tag"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    slug = db.Column(db.String(64), unique=True)

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __reper(self):
        return '<tag {}>'.format(self.name)

app.py
from flask import Flask
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy


from config import Configuartion  # import configuration data.

app = Flask(__name__)
# use values from our configuration object
app.config.from_object(Configuartion)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

entries/blueprint.py
from flask import Blueprint, render_template,request
from helpers import object_list
from models import Entry ,Tag

entries =Blueprint('entries', __name__, template_folder='templates')

def entry_list(template , query, **context ):
    search =request.args.get('q')
    if search:
        query=query.filter(
            (Entry.body.contains(search)) |
            (Entry.title.contains(search)) )
    return object_list(template, query, **context)

@entries.route('/')
def index():
    entries =Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)

@entries.route('/tags/')
def tag_index():
    tags =Tag.query.order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)

@entries.route('/tags/<slug>/')
def tag_detail(slug):
    tag =Tag.query.filter(Tag.slug == slug).first_or_404()
    entries =tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)

@entries.route('/<slug>/')
def detail(slug):
    entry =Entry.query.filter(Entry.slug == slug).first_or_404()
    return render_template('entries/detail.html', entry=entry)

main.py
from app import app, db  # import our flask app
import models
import views

from entries.blueprint import entries
app.register_blueprint(entries,url_prefix='/entries')

if __name__ == '__main__':
    app.run()

views.py
from flask import render_template, request
from app import app


@app.route('/')
def homepage():
    name = request.args.get('name')
    number = request.args.get('number')
    return render_template('homepage.html', name=name, number=number)

entries/templates/entries/base_entries.html
{% extends "base.html" %}

{% block sidebar %}
    <form class="form-inline well"  method="get" role="form">
            <div class="input-group">
                <input class="form-control input-xs" name="q" placeholder="Search ..." value="{{ request.args.get('q', "") }}">
                <span class="input-group-btn" >
                    <button class="btn btn-default" type="submit">Go</button>
                </span>
            </div>
    </form>
{% endblock  %}

{% block content%}
        {% include "includes/list.html" %}
{% endblock %}

entries/templates/entries/detail.html
{% extends "base.html" %}
{% block title %} {{ entry.title}} {% endblock  %}
{% block content_title %} {{entry.title}} {% endblock  %}
{% block sidebar %}
<ul class="well nav nav-list">
    <li><h4>Tags</h4></li>
    {% for tag in entry.tags  %}
        <li><a href="{{url_for('entries.tag_detail', slug=tag.slug)}}"> {{ tag.name }} </a></li>
    {% endfor %}
    <p>Published {{ entry.created_timestamp.strftime('%m/%d/%y')}}</p>
</ul>
{% endblock  %}

{% block content %}
    {{ entry.body }}
{% endblock  %}

entries/templates/entries/includes/list.html
{% for  entry in object_list.items  %}
    <p><a href="{{ url_for('entries.detail',slug=entry.slug )}}">{{ entry.title }}</a></p>
{% endfor %}

entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}
{% block title %} Tag {% endblock  %}
{% block content_title %} Tags{% endblock  %}

entries/templates/entries/tag_detail.html
{% extends "entries/base_entries.html" %}

{% block title %} Entries {% endblock  %}
{% block content_title %} Entries{% endblock  %}

entries/templates/entries/tag_index.html
{% extends "base.html" %}
{% block title  %} Tags {% endblock  %}
{% block content_title %} Tags {% endblock  %}
{% block content %}
    <ul>
        {% for tag in object_list.items  %}
            <li><a href="{{url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock  %}

templates/base.html
<!DOCTYPE html>
    <html lang="en">
        <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %} | My Blog</title>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
        <style type="text/css">
            body { padding-top: 60px; }
        </style>
        {% block extra_styles %}{% endblock %}
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
        {% block extra_scripts %}{% endblock %}
    </head>
<body class="{% block body_class %}{% endblock %}">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="#">{% block branding %}My Blog{% endblock %}</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                <li><a href="{{url_for('homepage')}}">Home</a></li>
                    <li><a href="{{url_for('entries.index')}}">Blog</a></li>
                    <li><a href="{{url_for('entries.tag_index')}}">Tags</a></li>
                    {% block extra_nav %}{% endblock %}
                </ul>
            </div>
        </div>
    </div>
<div class="container">
        <div class="row">
                    <div class="col-md-9">
                    <h1>{% block content_title %}{% endblock %}</h1>
                    {% block content %}{% endblock %}
                    </div>
            <div class="col-md-3">
                        {% block sidebar %}
                    <ul class="well nav nav-stacked">
                    <li><a href="#">Sidebar item</a></li>
                    </ul>
            {% endblock %}
            </div>
        </div>
<div class="row">
    <hr />
<footer>
    <p>&copy; Chucky</p>
</footer>
</div>
</div>
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% block content_title  %} Welcome to the blog {% endblock %}

{% block content %}
    {% if number %}
    <p>Your number is {{ number|int }} </p>
    <ul>
    {% for i in range(number|int) %}
    {% if i is divisibleby 2 %}
        <li>{{ i }}</li>
    {% endif %}
    {% endfor %}
    </ul>
    {% else %}
    <p>No number specified </p>
    {% endif %}
    <p> Your name is {{ name|default('<unkown>'),True }} .</p>

{% endblock %}

templates/includes/list.html
{% for  entry in object_list.items  %}
    <p><a href="{{ url_for('entries.detail',slug=entry.slug )}}">{{ entry.title }}</a></p>
{% endfor %}